### ISSUE TITLE
`error in error handling` when using `error()` in scripts

### ISSUE THREAD

**Issue by lupus590** [SquidDev-CC/mbs#10]
I'm using my [CC dev MC instance](https://github.com/CC-Hive/DevEnviroment) which includes this [resource pack](https://github.com/lupus590/CC-My-Code-Pack) for loading MBS.

Error occurs in MBS but not the vanilla shell.

`error("", 0)` doesn't have this issue.

**Comment by SquidDev** [comment]
Sadly this appears to be a bug in LuaJ. For instance, the following code fails:

```lua
local ok, err = xpcall(function() error() end, function(err) return err end)
-- false, "error in error handling".
```

I'd recommend using CC:Tweaked or enabling the cobalt runtime in CCTweaks.
