### ISSUE TITLE
[Suggestion] Update detector

### ISSUE THREAD

**Issue by lupus590** [SquidDev-CC/mbs#11]
I'll be willing to work on it, but I thought I should ask before I do.

**Comment by SquidDev** [comment]
I'm not too sure how I feel about this. I guess it could be useful, it seems a little overkill for such a small project.

I'm not sure when/where you're planning to fire it? I'm  reluctant to do it at startup, as I suspect that'd require it being a synchronous HTTP request and that'll just slow down booting.

**Comment by lupus590** [comment]
Updates can be identified by looking at the sha of the commit with from: https://api.github.com/repos/SquidDev-CC/mbs/branches/master
