### ISSUE TITLE
Can't use key Alt Gr with ch_FR layout

### ISSUE THREAD

**Issue by Ale32bit** [SquidDev-CC/mbs#19]
Title should say everything.
I can't type {, }, [, ], ~, ´, ¢, |, ¬, °, #, @, ¦

**Comment by SquidDev** [comment]
A temporary workaround would be to disable the `readline` module on your computer. I'm not sure how best to fix this, as I don't believe there's an easy way to detect `AltGr` being pressed, so we cannot distinguish between `C-M-*` and altgr.

**Comment by SquidDev** [comment]
Sorry, should really know better by now not to manage issues on mobile.
