### ISSUE TITLE
Installation guide invalid

### ISSUE THREAD

**Issue by lurr** [SquidDev-CC/mbs#2]
The installation file and root directory share the same name, `mbs`

Running `mbs install` creates a directory, `mbs`, which conflicts with the given command to download it `wget https://raw.githubusercontent.com/SquidDev-CC/mbs/master/mbs.lua mbs`

It works using `wget https://raw.githubusercontent.com/SquidDev-CC/mbs/master/mbs.lua mbs.lua`
Simply changing the installation instructions should solve it.

Barely an issue; but an issue nonetheless :)

**Comment by SquidDev** [comment]
Fixed! Apparently I accidentally committed some debugging changes - it's meant to install to `.mbs` instead. Thanks for the report.
