### ISSUE TITLE
Is it okay if I add your project into my package manager's repo

### ISSUE THREAD

**Issue by RubenHetKonijn** [SquidDev-CC/mbs#38]
Hey, is it okay if add your project into my package manager's repo, if you don't want it there please tell me and I'll not add it

**Comment by SquidDev** [comment]
Hey, thanks for asking! As long as you abide by the licence (so don't claim its your own work, etc...), feel free to do whatever!

**Comment by RubenHetKonijn** [comment]
Yeah if you want to check it out, it's at https://github.com/knijn/packium
