### ISSUE TITLE
uh, it appears to crash after editing a program and running it.

### ISSUE THREAD

**Issue by jebjordan** [SquidDev-CC/mbs#39]
After installing, (either on a pocket computer or a normal advanced one..

edit t.lua
-> put anything in it. ex: print("hello world")
run it from the edit screen,
it will output, the tabs at the top will kinda spazz and disappear, and then it'll shutdown/crash the computer once you click any button or wait a few seconds. 

expected it to be normal and show the output tab and just close that but yeah..

anyways.

- this is done on the atm6 modpack official server.

**Comment by Lupus590** [comment]
Possibly related #36
