### ISSUE TITLE
Program failure of fullscreen programs not visible

### ISSUE THREAD

**Issue by sewbacca** [SquidDev-CC/mbs#4]
If a fullscreen program throws an error, there will be no output to the user that this program has failed.

**Comment by SquidDev** [comment]
Hrmrrm, this'll be a pain to work around. There's a couple of potential options here:

 - Don't restore the screen if a program crashes. Instead, copy the program's buffer to the original window.
 - Defer printing the error message until the buffer has been restored. This won't work if people print additional information before crashing, but it might be cleaner.

**Comment by sewbacca** [comment]
I recommend the first option, because, if there is an error, then it's sometimes important to see, what output the program has produced (e. g. if a pixel is already drawn or not).
