### ISSUE TITLE
Using the edit program with long lines causes weirdness

### ISSUE THREAD

**Issue by apemanzilla** [SquidDev-CC/mbs#5]
If you edit a file and scroll horizontally towards the end of a line that goes beyond the end of the screen, you get some pretty weird behavior. It seems to cut off parts of the line visually or something? Kind of difficult to describe.

This doesn't seem to happen with `read()`.

**Comment by SquidDev** [comment]
I'm _pretty_ sure this is a vanilla CC issue, but yes - I have also noticed this.
